---
language: ruby
env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
before_install:
  - gem install bundler -v '~> 1.10.0'
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
gemfile:
  - Gemfile
notifications:
  email: false
