# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84125cd5570ed75fa8baaef46dac701fa4913f3b8c2004abc9e55209c6978d9f2d5186eb9de8ecd02ab002c1d62b5fa012ba39d767abc80a7e240c89b76f22d6

test:
  secret_key_base: 94778cb4aca9a63200848f7227901444b818c33d1ebcf8025f839ba15e5980a3ee0c5b100273eb9f41fc78bb345be12094a2a5a23fb0c24352ae982bd1b445f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
